[profile.default]
# Compilation
optimizer = true
optimizer_runs = 100
solc_version = "0.8.19"
# via_ir = true

# Testing
block_timestamp = 2592000 # as to be greater than epochFixTimeout
chain_id = 99 
gas_reports = ["*"] 
libs = ["node_modules", "lib"] 
sender = '0xf000000000000000000000000000000000000000' 
tx_origin = '0xf000000000000000000000000000000000000000' 
verbosity = 3 

[profile.ci.fuzz]
runs = 5000

[profile.default.fuzz]
runs = 100

[profile.default.invariant]
call_override = false # Override calls
depth = 100 # The number of times to run the invariant tests
fail_on_revert = true # Fail the test if the contract reverts
runs = 100 # The number of calls to make in the invariant tests

[profile.default.fmt]
int_types = "preserve"
number_underscore = "preserve"

[profile.default.rpc_endpoints]
mainnet = "${SCROLL_RPC_URL}"
tenderly = "${TENDERLY_FORK_URL}"
